
const KEY='my_ledger_data_v3', LEGACY_KEYS=['my_ledger_data_v2','my_ledger_v2','my_ledger_v1','my_ledger_backup_v2','my_ledger_backup_v1'], BACKUP_KEY='my_ledger_backup_v3', IDB_NAME='my_ledger_storage', IDB_STORE='snapshots', VERSION=2.8;
let storageMeta={revision:0,savedAt:0,writerId:(crypto?.randomUUID?crypto.randomUUID():String(Date.now())+'-'+Math.random())};
const ALLOWED_CURRENCIES=['CNY','RUB'];
const ALLOWED_TYPES=['bank','wallet','cash','card','other'];
const defaultCategories=['餐饮','购物','交通','房租','娱乐','学习','医疗','工资','水电','旅行','其他'];
const defaultDB={version:VERSION,rate:11,budget:0,dark:false,ledgerStartDate:localDate(),categories:[...defaultCategories],fxHistory:[{id:1,date:localDate(),rate:11}],accounts:[{id:1,name:'Сбербанк',type:'bank',currency:'RUB',initial:0,allowNegative:false,active:true},{id:2,name:'微信',type:'wallet',currency:'CNY',initial:0,allowNegative:false,active:true},{id:3,name:'现金',type:'cash',currency:'RUB',initial:0,allowNegative:false,active:true}],tx:[]};
let db, currentTxType='expense', lastPersistedRaw=null, loadedFromStorage=false;
function clone(o){return JSON.parse(JSON.stringify(o))}
function isFiniteNumber(v){return Number.isFinite(Number(v))}
function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function normalizeDate(v){const s=String(v??'').trim();const m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return null;const y=Number(m[1]),mo=Number(m[2]),day=Number(m[3]);const dt=new Date(y,mo-1,day);if(dt.getFullYear()!==y||dt.getMonth()!==mo-1||dt.getDate()!==day)return null;return `${m[1]}-${m[2]}-${m[3]}`}
function isValidLedgerDate(v){return !!normalizeDate(v)}
function nextId(items){return items.reduce((m,x)=>Math.max(m,Number(x.id)||0),0)+1}
function normalizeDB(raw){
  const d=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};
  const derivedStart=(()=>{const ds=normalizeDate(d.ledgerStartDate);if(ds)return ds;const dates=Array.isArray(d.tx)?d.tx.map(t=>normalizeDate(t?.date)).filter(Boolean).sort():[];return dates[0]||localDate()})();
  const out={version:VERSION,rate:isFiniteNumber(d.rate)&&Number(d.rate)>0?Number(d.rate):11,budget:isFiniteNumber(d.budget)&&Number(d.budget)>=0?Number(d.budget):0,dark:!!d.dark,ledgerStartDate:derivedStart,categories:[],fxHistory:[],accounts:[],tx:[]};
  const rawFx=Array.isArray(d.fxHistory)?d.fxHistory:[];
  const fxMap=new Map();
  for(const h of rawFx){const hd=normalizeDate(h?.date),hr=Number(h?.rate);if(hd&&hr>0&&Number.isFinite(hr))fxMap.set(hd,hr)}
  if(!fxMap.size) fxMap.set(derivedStart,out.rate);
  out.fxHistory=[...fxMap.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,rate],i)=>({id:i+1,date,rate}));
  const usedAcc=new Set();
  for(const a of Array.isArray(d.accounts)?d.accounts:[]){
    if(!a||typeof a!=='object')continue;
    let id=Number(a.id); if(!Number.isFinite(id)||id<=0||usedAcc.has(id))id=nextId(out.accounts); usedAcc.add(id);
    const currency=ALLOWED_CURRENCIES.includes(a.currency)?a.currency:'RUB';
    const type=ALLOWED_TYPES.includes(a.type)?a.type:'bank';
    const initial=isFiniteNumber(a.initial)?Number(a.initial):0;
    const allowNegative=a.allowNegative===true || (a.allowNegative==null && type==='card'); out.accounts.push({id,name:String(a.name??'未命名账户').trim()||'未命名账户',type,currency,initial,allowNegative,active:a.active!==false});
  }
  if(!out.accounts.length)out.accounts=clone(defaultDB.accounts);
  const accIds=new Set(out.accounts.map(a=>a.id));
  const cats=Array.isArray(d.categories)?d.categories.map(x=>String(x??'').trim()).filter(Boolean):[];
  out.categories=[...new Set(cats.length?cats:defaultCategories)];
  const usedTx=new Set();
  for(const t of Array.isArray(d.tx)?d.tx:[]){
    if(!t||typeof t!=='object')continue;
    let id=Number(t.id); if(!Number.isFinite(id)||id<=0||usedTx.has(id))id=nextId(out.tx); usedTx.add(id);
    const date=normalizeDate(t.date);
    if(!date)continue;
    if(t.type==='income'||t.type==='expense'){
      const account=Number(t.account),a=out.accounts.find(x=>x.id===account); const amount=Number(t.amount);
      if(!a||!accIds.has(account)||!(amount>0)||!ALLOWED_CURRENCIES.includes(t.currency))continue;
      const fxRate=t.currency==='CNY'?1:(isFiniteNumber(t.fxRate)&&Number(t.fxRate)>0?Number(t.fxRate):out.rate);
      const occurredAt=(typeof t.occurredAt==='string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(t.occurredAt) && t.occurredAt.startsWith(date+'T'))?t.occurredAt:(date+'T12:00');
      out.tx.push({id,type:t.type,amount,currency:t.currency,account,category:String(t.category||'其他'),date,note:String(t.note||''),fxRate,occurredAt,createdAt:Number(t.createdAt)||Date.now()});
    }else if(t.type==='transfer'){
      const from=Number(t.from),to=Number(t.to),fa=out.accounts.find(x=>x.id===from),ta=out.accounts.find(x=>x.id===to);
      const fromAmount=Number(t.fromAmount??t.amount),toAmount=Number(t.toAmount??t.amount);
      if(!fa||!ta||from===to||!(fromAmount>0)||!(toAmount>0))continue;
      const occurredAt=(typeof t.occurredAt==='string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(t.occurredAt) && t.occurredAt.startsWith(date+'T'))?t.occurredAt:(date+'T12:00');
      out.tx.push({id,type:'transfer',from,to,fromCurrency:fa.currency,toCurrency:ta.currency,fromAmount,toAmount,amount:fromAmount,currency:fa.currency,date,note:String(t.note||''),occurredAt,createdAt:Number(t.createdAt)||Date.now()});
    }
  }
  return out;
}
function parseStoragePayload(raw){try{const parsed=JSON.parse(raw);if(parsed&&parsed.data&&typeof parsed.data==='object'&&!Array.isArray(parsed.data))return{data:parsed.data,meta:{revision:Number(parsed.revision)||0,savedAt:Number(parsed.savedAt)||0,writerId:String(parsed.writerId||'')}};return{data:parsed,meta:{revision:0,savedAt:0,writerId:''}}}catch{return null}}
function storageEntry(key){try{const raw=localStorage.getItem(key);if(!raw)return null;const p=parseStoragePayload(raw);return p?{key,raw,...p}:null}catch{return null}}
function readStoredEntries(){return [KEY,BACKUP_KEY,...LEGACY_KEYS].map(storageEntry).filter(Boolean)}
function bestLocalEntry(){return readStoredEntries().sort((a,b)=>(Number(b.meta.savedAt)||0)-(Number(a.meta.savedAt)||0)||(Number(b.meta.revision)||0)-(Number(a.meta.revision)||0))[0]||null}
function storageEnvelope(data,meta){return JSON.stringify({schema:'my-ledger-storage',storageVersion:1,revision:meta.revision,savedAt:meta.savedAt,writerId:meta.writerId,data})}
function adoptMeta(meta){storageMeta={revision:Number(meta?.revision)||0,savedAt:Number(meta?.savedAt)||0,writerId:storageMeta.writerId};lastPersistedRaw=JSON.stringify(db)}
function loadDB(){loadedFromStorage=false;const best=bestLocalEntry();if(best){const loaded=normalizeDB(best.data);loadedFromStorage=true;adoptMeta(best.meta);if(best.key!==KEY)setTimeout(()=>{try{persist()}catch{}},0);return loaded}lastPersistedRaw=null;storageMeta={revision:0,savedAt:0,writerId:storageMeta.writerId};return clone(defaultDB)}
async function idbOpen(){return await new Promise((resolve,reject)=>{try{const req=indexedDB.open(IDB_NAME,2);req.onupgradeneeded=()=>{const dbx=req.result;if(!dbx.objectStoreNames.contains(IDB_STORE))dbx.createObjectStore(IDB_STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)}catch(e){reject(e)}})}
async function idbPut(raw,meta){try{const dbx=await idbOpen();const prev=await new Promise(res=>{const req=dbx.transaction(IDB_STORE,'readonly').objectStore(IDB_STORE).get('latest');req.onsuccess=()=>res(req.result);req.onerror=()=>res(null)});await new Promise((resolve,reject)=>{const tx=dbx.transaction(IDB_STORE,'readwrite'),store=tx.objectStore(IDB_STORE);if(prev?.raw)store.put({...prev,id:'previous'});store.put({id:'latest',raw,revision:meta.revision,savedAt:meta.savedAt,writerId:meta.writerId});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});dbx.close()}catch{}}
async function idbBest(){try{const dbx=await idbOpen();const all=await new Promise(res=>{const req=dbx.transaction(IDB_STORE,'readonly').objectStore(IDB_STORE).getAll();req.onsuccess=()=>res(req.result||[]);req.onerror=()=>res([])});dbx.close();return all.sort((a,b)=>(Number(b.savedAt)||0)-(Number(a.savedAt)||0)||(Number(b.revision)||0)-(Number(a.revision)||0))[0]||null}catch{return null}}
function markStorageStatus(label='已自动保存'){const el=document.getElementById('storageStatus');const tm=document.getElementById('storageUpdated');if(el)el.textContent=label;if(tm)tm.textContent='最近保存：'+new Date().toLocaleString('zh-CN')}
function persist(){const data=clone(db),meta={revision:Math.max(0,Number(storageMeta.revision)||0)+1,savedAt:Date.now(),writerId:storageMeta.writerId},wrapped=storageEnvelope(data,meta);try{localStorage.setItem(KEY,wrapped)}catch(e){throw e}try{localStorage.setItem(BACKUP_KEY,wrapped)}catch{}storageMeta={...meta};lastPersistedRaw=JSON.stringify(db);markStorageStatus('已自动保存');idbPut(wrapped,meta)}
async function recoverBestLocalBackup(){try{const idb=await idbBest(),local=bestLocalEntry(),localSaved=Number(local?.meta?.savedAt)||0,idbSaved=Number(idb?.savedAt)||0;if(!idb?.raw||idbSaved<=localSaved)return;const parsed=parseStoragePayload(idb.raw);if(!parsed?.data)return;db=normalizeDB(parsed.data);storageMeta={revision:Number(idb.revision)||0,savedAt:idbSaved,writerId:storageMeta.writerId};loadedFromStorage=true;const wrapped=storageEnvelope(db,storageMeta);try{localStorage.setItem(KEY,wrapped);localStorage.setItem(BACKUP_KEY,wrapped)}catch{}lastPersistedRaw=JSON.stringify(db);render();toast('已从较新的本机自动副本恢复数据')}catch{}}

function latestStorageMeta(){return storageEntry(KEY)?.meta||null}
function syncBeforeMutation(){const latest=latestStorageMeta();if(!latest)return true;const lr=Number(latest.revision)||0,ls=Number(latest.savedAt)||0,mr=Number(storageMeta.revision)||0,ms=Number(storageMeta.savedAt)||0;if((lr>mr||ls>ms)&&String(latest.writerId)!==String(storageMeta.writerId)){refreshFromStorage();toast('检测到另一个页面刚刚修改了账本，已先同步最新数据；请重新提交这次操作。');return false}return true}
function safeCommit(mutator,msg){const before=clone(db);try{if(!syncBeforeMutation())return false;mutator();persist();render();if(msg)toast(msg);return true}catch(e){db=before;try{persist()}catch{}render();const isQuota=e?.name==='QuotaExceededError'||e?.code===22||e?.code===1014;toast(isQuota?'保存失败：浏览器存储空间可能已满':(e?.message||'保存失败，请重试'));return false}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(n,c){const v=Number(n);const safe=Number.isFinite(v)?v:0;return c==='CNY'?'¥'+safe.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}):'₽'+safe.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})}
function txCnyValue(t){const amount=Number(t.amount??0);if(t.currency==='CNY')return amount;const rate=isFiniteNumber(t.fxRate)&&Number(t.fxRate)>0?Number(t.fxRate):db.rate;return amount/rate}
function accBy(id){return db.accounts.find(a=>Number(a.id)===Number(id))}
function accountBalances(){const b={};db.accounts.forEach(a=>b[a.id]=Number(a.initial)||0);for(const t of db.tx){if(t.type==='income')b[t.account]=(b[t.account]||0)+Number(t.amount||0);else if(t.type==='expense')b[t.account]=(b[t.account]||0)-Number(t.amount||0);else if(t.type==='transfer'){b[t.from]=(b[t.from]||0)-Number(t.fromAmount||t.amount||0);b[t.to]=(b[t.to]||0)+Number(t.toAmount||t.amount||0)}}return b}
function monthKey(date){if(date instanceof Date && !Number.isNaN(date.getTime())){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;}const s=String(date??'').trim();return /^\d{4}-\d{2}-\d{2}$/.test(s)?s.slice(0,7):/^\d{4}-\d{2}/.test(s)?s.slice(0,7):''}
function selectedMonth(){return document.getElementById('statMonth')?.value||monthKey(new Date())}
function transactionsForMonth(ym){return db.tx.filter(t=>monthKey(t.date)===ym)}
function summaryMonth(ym){let inc=0,exp=0,incCny=0,incRub=0,expCny=0,expRub=0;const cats={};for(const t of db.tx){if(monthKey(t.date)!==ym)continue;if(t.type==='income'){const amount=Number(t.amount||0);if(!Number.isFinite(amount))continue;const v=txCnyValue(t);if(Number.isFinite(v)){inc+=v;if(t.currency==='CNY')incCny+=amount;else incRub+=amount}}else if(t.type==='expense'){const amount=Number(t.amount||0);if(!Number.isFinite(amount))continue;const v=txCnyValue(t);if(Number.isFinite(v)){exp+=v;if(t.currency==='CNY')expCny+=amount;else expRub+=amount;const cat=t.category||'其他';cats[cat]=(cats[cat]||0)+v}}}return{inc,exp,cats,incCny,incRub,expCny,expRub}}

function monthNativeText(s,kind){
  if(kind==='income'){
    const parts=[]; if(s.incCny>0)parts.push(fmt(s.incCny,'CNY')); if(s.incRub>0)parts.push(fmt(s.incRub,'RUB')); return parts.length?parts.join(' + '):'—';
  }
  if(kind==='expense'){
    const parts=[]; if(s.expCny>0)parts.push(fmt(s.expCny,'CNY')); if(s.expRub>0)parts.push(fmt(s.expRub,'RUB')); return parts.length?parts.join(' + '):'—';
  }
  return '按人民币折算';
}

function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1900)}
function render(){renderHome();populateFilters();renderBills();renderAccounts();renderStats();renderCategories();renderSettings();document.body.classList.toggle('dark',db.dark)}
function renderHome(){
  const b=accountBalances();
  const cny=db.accounts.filter(a=>a.currency==='CNY').reduce((sum,a)=>sum+(b[a.id]||0),0);
  const rub=db.accounts.filter(a=>a.currency==='RUB').reduce((sum,a)=>sum+(b[a.id]||0),0);
  document.getElementById('cnyTotal').textContent=fmt(cny,'CNY');
  document.getElementById('rubTotal').textContent=fmt(rub,'RUB');
  document.getElementById('totalCny').textContent=fmt(cny+rub/db.rate,'CNY');
  const ym=localDate().slice(0,7);
  const s=summaryMonth(ym);
  const today=localDate();
  const todayExp=db.tx.filter(t=>normalizeDate(t.date)===today&&t.type==='expense').reduce((sum,t)=>sum+txCnyValue(t),0);
  document.getElementById('monthLabel').textContent=ym;
  document.getElementById('homeIncome').textContent=fmt(s.inc,'CNY');
  document.getElementById('homeExpense').textContent=fmt(s.exp,'CNY');
  document.getElementById('homeNet').textContent=fmt(s.inc-s.exp,'CNY');
  document.getElementById('homeIncomeNative').textContent=monthNativeText(s,'income');
  document.getElementById('homeExpenseNative').textContent=monthNativeText(s,'expense');
  const over=db.budget>0&&s.exp>db.budget;
  document.getElementById('budgetText').textContent=db.budget>0?(over?`已超预算 ${fmt(s.exp-db.budget,'CNY')}`:`${fmt(s.exp,'CNY')} / ${fmt(db.budget,'CNY')}`):'未设置';
  document.getElementById('budgetText').className=over?'warning':'muted';
  document.getElementById('budgetBar').style.width=db.budget>0?Math.min(100,s.exp/db.budget*100)+'%':'0%';
  const items=db.accounts.map(a=>{const bal=b[a.id]||0;return `<div class="item row"><div><div class="titleline"><span>${a.currency==='CNY'?'🇨🇳':'🇷🇺'}</span><b>${esc(a.name)}</b></div><small class="muted">${typeLabel(a.type)} · ${a.currency}</small></div><b>${fmt(bal,a.currency)}</b></div>`}).join('');
  document.getElementById('accountHome').innerHTML=items||'<div class="empty">还没有账户</div>';
  const recent=db.tx.slice().sort((a,b)=>txSortKey(b).localeCompare(txSortKey(a))||Number(b.createdAt||0)-Number(a.createdAt||0)||Number(b.id)-Number(a.id)).slice(0,6);
  document.getElementById('recent').innerHTML=recent.map(renderTxRow).join('')||'<div class="empty">还没有账单，点击“＋ 记一笔”开始。</div>';
  const updated=document.getElementById('homeUpdated');
  if(updated)updated.innerHTML='<span class="live-dot"></span>刚刚更新 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
  const ht=document.getElementById('homeToday');
  if(ht)ht.textContent=`今日支出 ${fmt(todayExp,'CNY')}（按历史汇率折算）`;
}

function renderTxRow(t){const sign=t.type==='income'?'+':t.type==='expense'?'−':'';let label='';if(t.type==='transfer'){const f=accBy(t.from),to=accBy(t.to);label=`${f?.name||'已删除'} → ${to?.name||'已删除'}`;if(t.fromCurrency!==t.toCurrency)label+=` · 换汇 ${fmt(t.fromAmount,t.fromCurrency)} → ${fmt(t.toAmount,t.toCurrency)}`}else label=`${accBy(t.account)?.name||'已删除'} · ${t.category||''}`;const time=(String(t.occurredAt||'').match(/T(\d{2}:\d{2})/)||[])[1]||'';return `<div class="item row"><div style="min-width:0"><div class="titleline"><span>${t.type==='income'?'💰':t.type==='expense'?'🧾':'↔️'}</span><b style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(t.note||t.category||'无备注')}</b></div><small class="muted">${esc(t.date)}${time?' '+time:''} · ${esc(label)}</small></div><div style="text-align:right"><b class="amount ${t.type==='income'?'plus':t.type==='expense'?'minus':''}">${sign}${fmt(t.amount??t.fromAmount,t.currency||t.fromCurrency)}</b><br><button class="link muted" onclick="event.stopPropagation();editTx(${t.id})">编辑</button> <button class="link muted" onclick="event.stopPropagation();deleteTx(${t.id})">删除</button></div></div>`}
function populateFilters(){const months=[...new Set(db.tx.map(t=>monthKey(t.date)).filter(Boolean))].sort().reverse();const mf=document.getElementById('monthFilter'),prev=mf.value||'all';mf.innerHTML='<option value="all">全部月份</option>'+months.map(m=>`<option value="${m}">${m}</option>`).join('');if(months.includes(prev))mf.value=prev;const sm=document.getElementById('statMonth'),cur=sm.value||monthKey(new Date());const statMonths=[...new Set([...months,monthKey(new Date())])].sort().reverse();sm.innerHTML=statMonths.map(m=>`<option value="${m}">${m}</option>`).join('');sm.value=statMonths.includes(cur)?cur:statMonths[0];const af=document.getElementById('accountFilter'),ap=af.value||'all';af.innerHTML='<option value="all">全部账户</option>'+db.accounts.map(a=>`<option value="${a.id}">${esc(a.name)} (${a.currency})</option>`).join('');if(db.accounts.some(a=>String(a.id)===String(ap)))af.value=ap;const cf=document.getElementById('categoryFilter'),cp=cf.value||'all';cf.innerHTML='<option value="all">全部分类</option>'+db.categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(db.categories.includes(cp))cf.value=cp}
function renderBills(){let list=[...db.tx].sort((a,b)=>String(b.date).localeCompare(String(a.date))||Number(b.id)-Number(a.id));const q=(document.getElementById('search')?.value||'').trim().toLowerCase(),mf=document.getElementById('monthFilter')?.value||'all',tf=document.getElementById('typeFilter')?.value||'all',cf=document.getElementById('currencyFilter')?.value||'all',af=document.getElementById('accountFilter')?.value||'all',catf=document.getElementById('categoryFilter')?.value||'all';list=list.filter(t=>{const f=accBy(t.account),from=accBy(t.from),to=accBy(t.to);const searchBlob=[t.note,t.category,f?.name,from?.name,to?.name,t.date,t.currency,t.fromCurrency,t.toCurrency].filter(Boolean).join(' ').toLowerCase();const currOk=cf==='all'||t.currency===cf||t.fromCurrency===cf||t.toCurrency===cf;const accountOk=af==='all'||t.account===Number(af)||t.from===Number(af)||t.to===Number(af);const categoryOk=catf==='all'||t.category===catf;return(!q||searchBlob.includes(q))&&(mf==='all'||monthKey(t.date)===mf)&&(tf==='all'||t.type===tf)&&currOk&&accountOk&&categoryOk});document.getElementById('billCount').textContent=`${list.length} 条`;document.getElementById('billList').innerHTML=list.map(renderTxRow).join('')||'<div class="empty">没有符合条件的账单</div>'}
function renderAccounts(){const b=accountBalances();document.getElementById('accountList').innerHTML=db.accounts.map(a=>{const hasTx=db.tx.some(t=>t.account===a.id||t.from===a.id||t.to===a.id);return `<div class="item row"><div><div class="titleline"><b>${esc(a.name)}</b><span class="pill">${typeLabel(a.type)}</span>${a.active===false?'<span class="pill">已停用</span>':''}</div><small class="muted">${a.currency} · 初始 ${fmt(a.initial,a.currency)} · ${a.allowNegative?'允许负余额':'不允许负余额'}</small><br><small class="muted">当前余额：${fmt(b[a.id]||0,a.currency)}</small></div><div><button class="secondary" onclick="editAccount(${a.id})">编辑</button> ${hasTx?`<button class="secondary" onclick="toggleAccountActive(${a.id})">${a.active===false?'启用':'停用'}</button>`:`<button class="danger" onclick="deleteAccount(${a.id})">删除</button>`}</div></div>`}).join('')||'<div class="empty">暂无账户</div>'}
function typeLabel(t){return({bank:'银行',wallet:'电子钱包',cash:'现金',card:'银行卡/信用卡',other:'其他'}[t]||'其他')}
function renderStats(){const ym=selectedMonth(),s=summaryMonth(ym);document.getElementById('monthIn').textContent=fmt(s.inc,'CNY');document.getElementById('monthOut').textContent=fmt(s.exp,'CNY');const entries=Object.entries(s.cats).sort((a,b)=>b[1]-a[1]);const max=Math.max(...entries.map(x=>x[1]),1);document.getElementById('categoryStats').innerHTML=entries.map(([k,v])=>`<div style="margin:12px 0"><div class="row"><span>${esc(k)}</span><b>${fmt(v,'CNY')}</b></div><div class="statbar"><i style="width:${v/max*100}%"></i></div></div>`).join('')||'<div class="empty">这个月还没有支出</div>';const dates=[];const base=new Date(`${ym}-01T12:00:00`);for(let i=5;i>=0;i--){const d=new Date(base.getFullYear(),base.getMonth()-i,1);dates.push(monthKey(d))}const vals=dates.map(m=>summaryMonth(m).exp),maxV=Math.max(...vals,1);document.getElementById('sixMonthChart').innerHTML=dates.map((m,i)=>`<div class="col"><b style="font-size:10px">${fmt(vals[i],'CNY')}</b><i style="height:${vals[i]/maxV*135}px"></i><span>${m.slice(5)}</span></div>`).join('')}
function renderCategories(preserve=''){const list=document.getElementById('categoryList');list.innerHTML=db.categories.map(c=>`<div class="item row"><span>${esc(c)}</span><button class="danger category-remove" data-category="${esc(c)}">删除</button></div>`).join('');const sel=document.getElementById('txCategory');const cur=preserve||sel.value;let cats=[...db.categories];if(cur&& !cats.includes(cur))cats.unshift(cur);sel.innerHTML=cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(cur)sel.value=cur}
function renderFxHistory(){const el=document.getElementById('fxHistoryList');if(!el)return;const rows=[...db.fxHistory].sort((a,b)=>b.date.localeCompare(a.date)).map(h=>`<div class="item row"><span>${esc(h.date)}</span><b>1 CNY = ${Number(h.rate).toFixed(4)} RUB</b><button class="link muted" onclick="removeFxHistory('${esc(h.date)}')">删除</button></div>`).join('');el.innerHTML=rows||'<div class="empty">暂无汇率历史</div>'}
function renderSettings(){const active=document.activeElement;const inSettings=!!active?.closest?.('#page-settings');if(!inSettings){document.getElementById('rateInput').value=db.rate;document.getElementById('budgetInput').value=db.budget||0;document.getElementById('ledgerStartDate').value=db.ledgerStartDate||localDate();document.getElementById('darkMode').checked=db.dark}renderFxHistory()}
function showPage(id,btn){['home','bills','accounts','stats','settings'].forEach(p=>document.getElementById('page-'+p).classList.toggle('hidden',p!==id));document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));const active=document.querySelector(`.nav button[data-page="${id}"]`);if(active)active.classList.add('active');if(id==='bills')renderBills();if(id==='accounts')renderAccounts();if(id==='stats')renderStats()}
function openTx(id=null){const t=id?db.tx.find(x=>Number(x.id)===Number(id)):null;fillTxForm(!!t);document.getElementById('editTxId').value='';document.getElementById('txTitle').textContent='记一笔';document.getElementById('txDate').value=localDate();document.getElementById('txTime').value=new Date().toTimeString().slice(0,5);document.getElementById('txNote').value='';document.getElementById('txAmount').value='';document.getElementById('trFromAmount').value='';document.getElementById('trToAmount').value='';setTxType('expense');if(t){document.getElementById('editTxId').value=t.id;document.getElementById('txTitle').textContent='编辑账单';document.getElementById('txDate').value=t.date;document.getElementById('txTime').value=(String(t.occurredAt||'').match(/T(\d{2}:\d{2})/)||[])[1]||'12:00';document.getElementById('txNote').value=t.note||'';setTxType(t.type);if(t.type==='transfer'){document.getElementById('trFrom').value=t.from;document.getElementById('trTo').value=t.to;document.getElementById('trFromAmount').value=t.fromAmount??t.amount;document.getElementById('trToAmount').value=t.toAmount??t.amount;syncTransferCurrency();document.getElementById('trFromAmount').value=t.fromAmount??t.amount;document.getElementById('trToAmount').value=t.toAmount??t.amount;updateTransferRateText()}else{document.getElementById('txCurrency').value=t.currency;syncTxAccountToCurrency(t.account);document.getElementById('txAccount').value=t.account;document.getElementById('txAmount').value=t.amount;renderCategories(t.category);document.getElementById('txCategory').value=t.category||db.categories[0]}}else{const first=db.accounts.find(a=>a.active!==false);if(first){document.getElementById('txCurrency').value=first.currency;syncTxAccountToCurrency(first.id);document.getElementById('txAccount').value=first.id;}const from=document.getElementById('trFrom'),to=document.getElementById('trTo');if(from.options.length){from.selectedIndex=0;if(to.options.length>1)to.selectedIndex=1;syncTransferCurrency()}}document.getElementById('txModal').classList.add('show')}
function fillTxForm(includeInactive=false){const currencies=[...new Set(db.accounts.map(a=>a.currency))];const sel=document.getElementById('txCurrency');sel.innerHTML=currencies.map(c=>`<option value="${c}">${c==='CNY'?'🇨🇳':'🇷🇺'} ${c}</option>`).join('');const opts=db.accounts.filter(a=>includeInactive||a.active!==false).map(a=>`<option value="${a.id}">${esc(a.name)} (${a.currency})${a.active===false?' · 已停用':''}</option>`).join('');document.getElementById('txAccount').innerHTML=opts;document.getElementById('trFrom').innerHTML=opts;document.getElementById('trTo').innerHTML=opts;document.getElementById('trFromAmount').value='';document.getElementById('trToAmount').value='';if(currencies.length)sel.value=currencies[0];const fromSel=document.getElementById('trFrom'),toSel=document.getElementById('trTo');if(fromSel.options.length){fromSel.selectedIndex=0;if(toSel.options.length>1)toSel.selectedIndex=1;}}
function setTxType(t){currentTxType=t;document.getElementById('normalFields').classList.toggle('hidden',t==='transfer');document.getElementById('transferFields').classList.toggle('hidden',t!=='transfer');['expense','income','transfer'].forEach(x=>document.getElementById('tab'+x[0].toUpperCase()+x.slice(1)).classList.toggle('active',x===t));if(t==='transfer')updateTransferRateText()}
function syncTxAccountToCurrency(preferredId=null){const c=document.getElementById('txCurrency').value;const opts=db.accounts.filter(a=>a.currency===c&&(a.active!==false||Number(a.id)===Number(preferredId))).map(a=>`<option value="${a.id}">${esc(a.name)} (${a.currency})${a.active===false?' · 已停用':''}</option>`).join('');document.getElementById('txAccount').innerHTML=opts||'<option value="">暂无该币种账户</option>'}
function syncTransferCurrency(){const f=accBy(document.getElementById('trFrom').value),to=accBy(document.getElementById('trTo').value);if(f&&to&&f.currency===to.currency&&document.getElementById('trFromAmount').value)document.getElementById('trToAmount').value=document.getElementById('trFromAmount').value;else if(f&&to&&f.currency!==to.currency)document.getElementById('trToAmount').value='';updateTransferRateText()}
function updateTransferRateText(){const f=accBy(document.getElementById('trFrom').value),to=accBy(document.getElementById('trTo').value),a=Number(document.getElementById('trFromAmount').value||0),b=Number(document.getElementById('trToAmount').value||0);document.getElementById('trRateText').textContent=f&&to?a>0?(b/a).toFixed(6)+` ${to.currency}/${f.currency}`:'—':'—'}
function balancesFor(txs){const b={};db.accounts.forEach(a=>b[a.id]=Number(a.initial)||0);for(const t of txs){if(t.type==='income')b[t.account]=(b[t.account]||0)+Number(t.amount||0);else if(t.type==='expense')b[t.account]=(b[t.account]||0)-Number(t.amount||0);else if(t.type==='transfer'){b[t.from]=(b[t.from]||0)-Number(t.fromAmount||t.amount||0);b[t.to]=(b[t.to]||0)+Number(t.toAmount||t.amount||0)}}return b}
function txSortKey(t){return String(t.occurredAt||(`${normalizeDate(t.date)||'9999-99-99'}T12:00`))}
function sortTxChronologically(txs){return [...txs].sort((a,b)=>txSortKey(a).localeCompare(txSortKey(b))||Number(a.createdAt||0)-Number(b.createdAt||0)||Number(a.id||0)-Number(b.id||0))}
function validateAccountTimeline(scopeIds=null,txs=db.tx){const scope=scopeIds?new Set([...scopeIds].map(Number)):null;const balances={};for(const a of db.accounts)balances[a.id]=Number(a.initial)||0;for(const t of sortTxChronologically(txs)){if(t.type==='income'){balances[t.account]=(balances[t.account]||0)+Number(t.amount||0);const a=accBy(t.account);if(a&&(!scope||scope.has(Number(a.id)))&&!a.allowNegative&&(balances[a.id]||0)<-0.000001)return `账户“${a.name}”在 ${t.date} 后出现负余额 ${fmt(balances[a.id],a.currency)}。`;}else if(t.type==='expense'){balances[t.account]=(balances[t.account]||0)-Number(t.amount||0);const a=accBy(t.account);if(a&&(!scope||scope.has(Number(a.id)))&&!a.allowNegative&&(balances[a.id]||0)<-0.000001)return `账户“${a.name}”在 ${t.date} 后余额不足（${fmt(balances[a.id],a.currency)}）。`;}else if(t.type==='transfer'){balances[t.from]=(balances[t.from]||0)-Number(t.fromAmount||t.amount||0);balances[t.to]=(balances[t.to]||0)+Number(t.toAmount||t.amount||0);const fa=accBy(t.from),ta=accBy(t.to);if(fa&&(!scope||scope.has(Number(fa.id)))&&!fa.allowNegative&&(balances[fa.id]||0)<-0.000001)return `账户“${fa.name}”在 ${t.date} 转出后余额不足（${fmt(balances[fa.id],fa.currency)}）。`;if(ta&&(!scope||scope.has(Number(ta.id)))&&!ta.allowNegative&&(balances[ta.id]||0)<-0.000001)return `账户“${ta.name}”在 ${t.date} 转入后出现异常负余额（${fmt(balances[ta.id],ta.currency)}）。`;}}return ''}
function touchedAccounts(t){const s=new Set();if(!t)return s;if(t.type==='transfer'){s.add(Number(t.from));s.add(Number(t.to))}else if(t.account!=null)s.add(Number(t.account));return s}
function validateBalances(nextRecord,replaceId=0){const txs=db.tx.filter(t=>Number(t.id)!==Number(replaceId));const old=db.tx.find(t=>Number(t.id)===Number(replaceId));txs.push(nextRecord);return validateAccountTimeline(new Set([...touchedAccounts(nextRecord),...touchedAccounts(old)]),txs)}
function validateBalances(nextRecord,replaceId=0){const txs=db.tx.filter(t=>Number(t.id)!==Number(replaceId));txs.push(nextRecord);const original=db.tx;db.tx=txs;const err=validateAccountTimeline();db.tx=original;return err}
function rateForDate(date){const d=normalizeDate(date)||localDate();const hist=[...db.fxHistory].filter(h=>normalizeDate(h.date)&&Number(h.rate)>0).sort((a,b)=>a.date.localeCompare(b.date));let chosen=null;for(const h of hist){if(h.date<=d)chosen=h;else break}return Number(chosen?.rate)||Number(db.rate)||11}
function applyDefaultFX(){const f=accBy(document.getElementById('trFrom').value),to=accBy(document.getElementById('trTo').value),a=Number(document.getElementById('trFromAmount').value||0),d=document.getElementById('txDate').value,rate=rateForDate(d);if(!f||!to||!(a>0))return toast('先选择账户并填写转出金额');if(f.currency===to.currency){document.getElementById('trToAmount').value=a}else if(f.currency==='CNY'&&to.currency==='RUB'){document.getElementById('trToAmount').value=(a*rate).toFixed(2)}else if(f.currency==='RUB'&&to.currency==='CNY'){document.getElementById('trToAmount').value=(a/rate).toFixed(2)}updateTransferRateText();toast(`已按 ${d||'今天'} 历史汇率计算`)}
function saveTx(){const editId=Number(document.getElementById('editTxId').value||0),type=currentTxType,date=document.getElementById('txDate').value,time=document.getElementById('txTime').value||'12:00',note=document.getElementById('txNote').value.trim();if(!isValidLedgerDate(date))return toast('日期无效');if(db.ledgerStartDate&&date<db.ledgerStartDate&&db.tx.length>0)return toast(`账单日期不能早于账本开始日期 ${db.ledgerStartDate}`);const old=editId?db.tx.find(t=>Number(t.id)===editId):null;let obj;if(type==='transfer'){const from=Number(document.getElementById('trFrom').value),to=Number(document.getElementById('trTo').value),fromA=Number(document.getElementById('trFromAmount').value),toA=Number(document.getElementById('trToAmount').value),fa=accBy(from),ta=accBy(to);if(!fa||!ta||from===to)return toast('请选择两个不同账户');if(!(fromA>0&&toA>0))return toast('请输入转出和转入金额');if(fa.currency===ta.currency&&Math.abs(fromA-toA)>0.000001)return toast('相同币种转账的转入金额必须等于转出金额');obj={type,from,to,fromCurrency:fa.currency,toCurrency:ta.currency,fromAmount:fromA,toAmount:toA,amount:fromA,currency:fa.currency,date,note,occurredAt:`${date}T${time}`};}else{const amount=Number(document.getElementById('txAmount').value),account=Number(document.getElementById('txAccount').value),currency=document.getElementById('txCurrency').value,category=document.getElementById('txCategory').value;const a=accBy(account);if(!(amount>0))return toast('金额必须大于 0');if(!a||a.currency!==currency)return toast('账户与币种不匹配');const fxRate=currency==='CNY'?1:(old&&old.type!=='transfer'&&old.currency===currency&&Number(old.fxRate)>0?Number(old.fxRate):rateForDate(date));obj={type,amount,currency,account,category,date,note,fxRate,occurredAt:`${date}T${time}`};}const record={id:editId||nextId(db.tx),createdAt:old?.createdAt||Date.now(),...obj};const balanceErr=validateBalances(record,editId);if(balanceErr)return toast(balanceErr);const ok=safeCommit(()=>{if(editId){const idx=db.tx.findIndex(t=>Number(t.id)===editId);if(idx<0)throw new Error('账单不存在');db.tx[idx]=record}else{db.tx.push(record);if(db.tx.length===1||!db.ledgerStartDate||record.date<db.ledgerStartDate)db.ledgerStartDate=record.date}},'账单已保存');if(ok){closeModal('txModal');requestAnimationFrame(render)}}
function editTx(id){openTx(id)}
function deleteTx(id){const t=db.tx.find(x=>x.id===id);if(!t)return;if(confirm('确定删除这笔账单吗？删除后余额和统计会立即更新。'))safeCommit(()=>{db.tx=db.tx.filter(x=>x.id!==id)},'账单已删除')}
function openAccount(id=null){document.getElementById('editAccId').value='';document.getElementById('accTitle').textContent='添加账户';document.getElementById('accName').value='';document.getElementById('accType').value='bank';document.getElementById('accCurrency').value='RUB';document.getElementById('accBalance').value='0';document.getElementById('accAllowNegative').checked=false;if(id){const a=accBy(id);if(!a)return;document.getElementById('editAccId').value=id;document.getElementById('accTitle').textContent='编辑账户';document.getElementById('accName').value=a.name;document.getElementById('accType').value=a.type||'bank';document.getElementById('accCurrency').value=a.currency;document.getElementById('accBalance').value=a.initial;document.getElementById('accAllowNegative').checked=!!a.allowNegative}document.getElementById('accModal').classList.add('show')}
function editAccount(id){openAccount(id)}
function saveAccount(){const id=Number(document.getElementById('editAccId').value||0),name=document.getElementById('accName').value.trim(),type=document.getElementById('accType').value,currency=document.getElementById('accCurrency').value,initial=Number(document.getElementById('accBalance').value||0),allowNegative=document.getElementById('accAllowNegative').checked;if(!name)return toast('请输入账户名称');if(!ALLOWED_CURRENCIES.includes(currency))return toast('目前只支持 CNY / RUB');if(!ALLOWED_TYPES.includes(type))return toast('账户类型不正确');if(!Number.isFinite(initial))return toast('初始余额不正确');const finalAllowNegative=allowNegative||type==='card';if(initial<0&&!finalAllowNegative)return toast('该账户不允许负余额，初始余额不能小于 0');if(id){const existing=accBy(id);if(!existing)return toast('账户不存在');const hasTx=db.tx.some(t=>t.account===id||t.from===id||t.to===id);if(hasTx&&existing.currency!==currency)return toast('已有账单的账户不能直接更换币种');if(hasTx&&Number(existing.initial)!==initial){if(!confirm(`账户“${existing.name}”已有历史账单。修改初始余额会影响全部历史余额和当前余额。\n\n确定继续吗？`))return;}}const ok=safeCommit(()=>{if(id){const a=accBy(id);if(!a)throw new Error('账户不存在');const oldInitial=a.initial;Object.assign(a,{name,type,currency,initial,allowNegative:finalAllowNegative});if(oldInitial!==initial&&!a.allowNegative){const timelineErr=validateAccountTimeline(new Set([id]));if(timelineErr)throw new Error(timelineErr)}}else{db.accounts.push({id:nextId(db.accounts),name,type,currency,initial,allowNegative:finalAllowNegative,active:true})}},id?'账户已修改':'账户已添加');if(ok)closeModal('accModal')}
function toggleAccountActive(id){const a=accBy(id);if(!a)return;const next=a.active===false;safeCommit(()=>{a.active=next},next?'账户已启用':'账户已停用')}
function deleteAccount(id){const hasTx=db.tx.some(t=>t.account===id||t.from===id||t.to===id);if(hasTx){return toast('已有历史账单的账户不能删除，可选择停用。')}if(!confirm('确定删除这个账户吗？'))return;safeCommit(()=>{db.accounts=db.accounts.filter(a=>a.id!==id)},'账户已删除')}
function manualRefresh(){const before=JSON.stringify(db);refreshFromStorage();if(JSON.stringify(db)===before)render();toast('已刷新')}
function openSettings(){showPage('settings')}
function addFxHistory(){const date=prompt('汇率日期（YYYY-MM-DD）',localDate());if(date===null)return;const d=normalizeDate(date);if(!d)return toast('日期无效');const v=Number(prompt('1 CNY = 多少 RUB',String(db.rate)));if(!(v>0)||!Number.isFinite(v))return toast('汇率无效');safeCommit(()=>{const existing=db.fxHistory.find(h=>h.date===d);if(existing)existing.rate=v;else db.fxHistory.push({id:nextId(db.fxHistory),date:d,rate:v});db.fxHistory.sort((a,b)=>a.date.localeCompare(b.date));if(d===localDate())db.rate=v},'历史汇率已保存')}
function removeFxHistory(date){const d=normalizeDate(date);if(!d)return;if(d===localDate())return toast('今天的当前汇率不能删除；可以直接修改当前汇率。');if(db.fxHistory.length<=1)return toast('至少保留一个汇率记录');if(confirm(`删除 ${d} 的汇率记录？老账单保存的历史汇率不会被改变。`))safeCommit(()=>{db.fxHistory=db.fxHistory.filter(h=>h.date!==d)},'汇率记录已删除')}
function saveSettings(){const r=Number(document.getElementById('rateInput').value),b=Number(document.getElementById('budgetInput').value||0),start=normalizeDate(document.getElementById('ledgerStartDate').value);if(!(r>0)||!Number.isFinite(r))return toast('汇率必须是大于 0 的数字');if(b<0||!Number.isFinite(b))return toast('预算必须是 0 或更大的数字');if(!start)return toast('账本开始日期无效');const earliest=[...db.tx.map(t=>normalizeDate(t.date)).filter(Boolean)].sort()[0];if(earliest&&start>earliest)return toast(`开始日期不能晚于已有最早账单 ${earliest}`);safeCommit(()=>{db.rate=r;db.budget=b;db.ledgerStartDate=start;db.dark=document.getElementById('darkMode').checked;const today=localDate(),h=db.fxHistory.find(x=>x.date===today);if(h)h.rate=r;else db.fxHistory.push({id:nextId(db.fxHistory),date:today,rate:r});db.fxHistory.sort((a,b)=>a.date.localeCompare(b.date))},'设置已保存')}
function toggleDark(){const before=clone(db);try{db.dark=document.getElementById('darkMode').checked;persist();document.body.classList.toggle('dark',db.dark)}catch(e){db=before;document.getElementById('darkMode').checked=db.dark;toast('主题保存失败')}}
function openCategoryManager(){renderCategories();document.getElementById('categoryModal').classList.add('show')}
function addCategory(){const c=prompt('请输入新分类');if(!c)return;const v=c.trim();if(!v)return;if(v.length>30)return toast('分类名称最多 30 个字');if(db.categories.includes(v))return toast('这个分类已经存在');safeCommit(()=>db.categories.push(v),'分类已添加');openCategoryManager()}
function removeCategory(c){if(db.categories.length<=1)return toast('至少保留一个分类');if(db.tx.some(t=>t.type!=='transfer'&&t.category===c))return toast('已有账单使用这个分类，不能删除；可以保留以保证历史记录完整。');if(confirm(`删除分类“${c}”？`)){safeCommit(()=>{db.categories=db.categories.filter(x=>x!==c)},'分类已删除');openCategoryManager()}}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`我的记账本备份_${localDate()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('备份已导出')}
function importData(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);if(!d||typeof d!=='object'||Array.isArray(d)||!Array.isArray(d.accounts)||!Array.isArray(d.tx))throw new Error('格式错误');const badDates=[];const badAmounts=[];d.tx.forEach((t,i)=>{if(!t||typeof t!=='object'){badDates.push(i+1);return}if(!isValidLedgerDate(t.date))badDates.push(i+1);if((t.type==='income'||t.type==='expense')&&!(Number(t.amount)>0))badAmounts.push(i+1);if(t.type==='transfer'&&(!(Number(t.fromAmount??t.amount)>0)||!(Number(t.toAmount??t.amount)>0)))badAmounts.push(i+1)});if(badDates.length)return toast(`导入失败：第 ${badDates.slice(0,5).join('、')} 条账单日期无效。不会自动改成今天，请修正后再导入。`);if(badAmounts.length)return toast(`导入失败：第 ${badAmounts.slice(0,5).join('、')} 条账单金额无效。`);const startDate=normalizeDate(d.ledgerStartDate);if(d.ledgerStartDate&&!startDate)return toast('导入失败：账本开始日期无效。');if(startDate&&d.tx.some(t=>normalizeDate(t.date)<startDate))return toast('导入失败：存在早于账本开始日期的账单，请先修正。');if(!confirm('导入会覆盖当前账本，建议先导出当前备份。继续吗？'))return;const normalized=normalizeDB(d);const before=db;db=normalized;const timelineErr=validateAccountTimeline();db=before;if(timelineErr)return toast('导入失败：'+timelineErr);const ok=safeCommit(()=>{db=normalized},'备份已导入');if(ok){const warning=validateAccountTimeline();if(warning)toast('备份已导入，但数据检查发现：'+warning)}}catch(err){toast('导入失败：文件格式不正确或包含无效数据')}finally{e.target.value=''}};reader.readAsText(file)}
function csvEscape(v){const s=String(v??'');return /[\",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function exportCSV(){const headers=['日期','类型','金额','币种','账户/转出账户','转入账户','分类','备注'];const rows=db.tx.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(t=>{const type=t.type==='income'?'收入':t.type==='expense'?'支出':'转账/换汇';const from=accBy(t.from)?.name||accBy(t.account)?.name||'';const to=accBy(t.to)?.name||'';const amount=t.type==='transfer'?`${t.fromAmount} → ${t.toAmount}`:t.amount;const currency=t.type==='transfer'?`${t.fromCurrency} → ${t.toCurrency}`:t.currency;return [t.date,type,amount,currency,from,to,t.category||'',t.note||''];});const csv=[headers,...rows].map(r=>r.map(csvEscape).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`我的记账本_${localDate()}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('CSV 已导出')}
function seedDemo(){if(db.tx.length&& !confirm('当前已有账单，继续会追加演示数据。'))return;const rub=db.accounts.find(a=>a.currency==='RUB'),cny=db.accounts.find(a=>a.currency==='CNY');if(!rub||!cny)return toast('演示数据需要至少一个 RUB 账户和一个 CNY 账户');const d=localDate(),base=nextId(db.tx);const demos=[{id:base,type:'income',amount:30000,currency:rub.currency,account:rub.id,category:db.categories.includes('工资')?'工资':db.categories[0],date:d,note:'演示收入',fxRate:db.rate,createdAt:Date.now()},{id:base+1,type:'expense',amount:450,currency:rub.currency,account:rub.id,category:db.categories.includes('餐饮')?'餐饮':db.categories[0],date:d,note:'午饭',fxRate:db.rate,createdAt:Date.now()+1},{id:base+2,type:'transfer',from:rub.id,to:cny.id,fromCurrency:'RUB',toCurrency:'CNY',fromAmount:5500,toAmount:Number((5500/db.rate).toFixed(2)),amount:5500,currency:'RUB',date:d,note:'演示换汇',createdAt:Date.now()+2}];const prospective=balancesFor([...db.tx,...demos]);for(const a of db.accounts){if(!a.allowNegative&&(prospective[a.id]||0)<-0.000001)return toast(`演示数据会让账户“${a.name}”出现负余额，请先给账户设置初始余额。`)}safeCommit(()=>db.tx.push(...demos),'已加入演示数据')}
function resetData(){if(!confirm('确定清空所有账户和账单吗？此操作不可撤销，请先导出备份。'))return;safeCommit(()=>{db=clone(defaultDB)},'已清空数据')}
function refreshFromStorage(){try{const found=bestLocalEntry();if(!found)return;const sr=Number(found.meta.revision)||0,ss=Number(found.meta.savedAt)||0,mr=Number(storageMeta.revision)||0,ms=Number(storageMeta.savedAt)||0;if(found.raw===lastPersistedRaw||(sr<=mr&&ss<=ms))return;db=normalizeDB(found.data);storageMeta={revision:sr,savedAt:ss,writerId:storageMeta.writerId};lastPersistedRaw=JSON.stringify(db);render();markStorageStatus('已同步最新数据')}catch(e){toast('同步数据失败')}}
window.addEventListener('focus',refreshFromStorage);window.addEventListener('pageshow',refreshFromStorage);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshFromStorage()});window.addEventListener('storage',e=>{if(e.key===KEY)refreshFromStorage()});setInterval(refreshFromStorage,2000);
function closeModal(id){document.getElementById(id).classList.remove('show')}
db=loadDB();
function init(){document.getElementById('today').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'});render();markStorageStatus('已自动保存');document.body.classList.toggle('dark',db.dark);setTxType('expense');document.querySelectorAll('#transferFields input').forEach(x=>x.addEventListener('input',updateTransferRateText));document.getElementById('trFrom').addEventListener('change',syncTransferCurrency);document.getElementById('trTo').addEventListener('change',syncTransferCurrency);document.getElementById('categoryList').addEventListener('click',e=>{const b=e.target.closest('.category-remove');if(b)removeCategory(b.dataset.category)});document.getElementById('accType').addEventListener('change',()=>{if(document.getElementById('accType').value==='card')document.getElementById('accAllowNegative').checked=true});if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}}
init();
recoverBestLocalBackup();
setTimeout(()=>{const integrityIssue=validateAccountTimeline();if(integrityIssue)toast('数据检查提示：'+integrityIssue)},700);
